# Title of the page
title: "Brian's Life"
# Your name
author: Brian Warmoth
# Show a link to LinkedIn in the header intro. Comment out to disable.
# linkedin: https://www.linkedin.com/in/brianwarmoth/
# Show a link at the top of your timeline to your main personal site
# Comment this out to disable
personal_site:
  url: https://warmoth.org/
  title: warmoth.org
# show today marker at end of timeline
show_today: true

# Your timeline is split into periods (e.g., decades, childhood/teens/adult, "Before Timeliner"/"After Timeliner", etc)
# Each period has a list of events formatted as `- date: title`. If you don't want to have period dividers, leave out the name field.
periods:
  - events:
    - October 1982: "ğŸ‘€ Brian is born in Illinois."
    - August 1999: "ğŸ‡¸ğŸ‡ª Brian temporarily relocates to Sweden."
- name: 2000's
    events:
    - July 2000: "ğŸŒ½ Brian returns to Illinois from Sweden."
    - August 2021: "ğŸ“š Brian enrolls at the University of Illinois Urbana-Champaign."
    - April 2004: "ğŸ­ Brian writes and directs his first full-length play."
    - June 2004: "ğŸ—½ Brian interns for and begins contributing to Wizard Magazine."
    - May 2005: "ğŸ­ Brian writes and directs his second full-length play."
    - May 2005: "ğŸ“ Brian graduates from the University of Illinois Urbana-Champaign."
    - May 2006: "ğŸ—½ Brian moves to New York to work for Wizard Magazine."
    - December 2007: "ğŸŒ­ Brian moves to Chicago to work for DDP."
    - January 2009: "ğŸ“º Brian begins contributing daily to MTV News."
- name: 2010's
    events:
    - June 2010: "ğŸ—¯ï¸ Brian begins contributing regularly to ComicsAlliance."
    - January 2011: "ğŸ—ï¸ Brian enrolls at Northwestern University's Medill School."
    - June 2011: "ğŸï¸ Brian begins contributing regularly to Independent Film Channel."
    - December 2011: "ğŸ“ Brian granduates from Northwestern University's Medill School."
    - January 2012: "ğŸ›ï¸ Brian moves to Washington, D.C."
    - May 2012: "ğŸ’¼ Brian joins Industry Dive."
    - January 2014: "ğŸ’¼ Brian joins American City Business Journals' Inno sites."
    - July 2016: "ğŸŒ Brian moves to the San Francisco Bay Area."
    - October 2016: "ğŸ“± Brian joins OSV."
- name: 2020's
    events:
    - October 2021: "ğŸ“± Brian joins Inside."
    - July 2023: "ğŸ’¬ Brian co-founds, launches <a href="https://www.aiartifacts.net/" target="_blank" rel="noopener"
        title="AI Artifacts">The AI Artifacts Podcast</a>."
    - November 2023: "ğŸ›’ Brian joins Digital Commerce 360."
